# Generated by Django 5.1 on 2024-08-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("panammun_panel", "0002_customuser_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="panammun_edition",
            name="actual",
            field=models.BooleanField(default=False),
        ),
    ]
