# Generated by Django 5.1 on 2024-08-26 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("panammun_panel", "0003_panammun_edition_actual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="panammun_edition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committees",
                to="panammun_panel.panammun_edition",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countries",
                to="panammun_panel.committee",
            ),
        ),
    ]
