# Generated by Django 5.1 on 2024-08-26 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("panammun_panel", "0005_alter_customuser_country"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal_user", "Normal_user"),
                    ("administrator", "Administrator"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="panammun_panel.country",
                unique=True,
            ),
        ),
    ]
