# Generated by Django 5.1 on 2024-09-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("panammun_panel", "0008_alter_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="language",
            field=models.CharField(max_length=3),
        ),
    ]
